// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjG7LAtdryN5zt4vtSCvPCqArXKQ6Fjk4',
    appId: '1:508664894857:web:d843798a2a362b5182bd58',
    messagingSenderId: '508664894857',
    projectId: 'mynotes-2114011',
    authDomain: 'mynotes-2114011.firebaseapp.com',
    storageBucket: 'mynotes-2114011.firebasestorage.app',
    measurementId: 'G-TW4RRCG23P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwyMUfw2S59IDdvEug1Uym1AfWLxgQ1s',
    appId: '1:508664894857:android:038d0c8f0110dee382bd58',
    messagingSenderId: '508664894857',
    projectId: 'mynotes-2114011',
    storageBucket: 'mynotes-2114011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqnComi6NIBvZCIjCaSng6OYUaeQf06gk',
    appId: '1:508664894857:ios:053608269273849282bd58',
    messagingSenderId: '508664894857',
    projectId: 'mynotes-2114011',
    storageBucket: 'mynotes-2114011.firebasestorage.app',
    iosBundleId: 'com.asad.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqnComi6NIBvZCIjCaSng6OYUaeQf06gk',
    appId: '1:508664894857:ios:053608269273849282bd58',
    messagingSenderId: '508664894857',
    projectId: 'mynotes-2114011',
    storageBucket: 'mynotes-2114011.firebasestorage.app',
    iosBundleId: 'com.asad.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjG7LAtdryN5zt4vtSCvPCqArXKQ6Fjk4',
    appId: '1:508664894857:web:b7e10fa414f608c282bd58',
    messagingSenderId: '508664894857',
    projectId: 'mynotes-2114011',
    authDomain: 'mynotes-2114011.firebaseapp.com',
    storageBucket: 'mynotes-2114011.firebasestorage.app',
    measurementId: 'G-TBF4HTYYEN',
  );
}
